CREATE TABLE `ai_channels` (
	`id` text PRIMARY KEY NOT NULL,
	`area` text NOT NULL,
	`provider` text NOT NULL,
	`name` text NOT NULL,
	`base_url` text NOT NULL,
	`models` text NOT NULL,
	`price_multiplier` real NOT NULL,
	`api_key_ciphertext` text NOT NULL,
	`api_key_iv` text NOT NULL,
	`enabled` integer NOT NULL,
	`version` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "ai_channels_area_check" CHECK("ai_channels"."area" in ('image', 'tts', 'video')),
	CONSTRAINT "ai_channels_name_check" CHECK(length("ai_channels"."name") > 0),
	CONSTRAINT "ai_channels_price_multiplier_check" CHECK("ai_channels"."price_multiplier" > 0),
	CONSTRAINT "ai_channels_version_check" CHECK("ai_channels"."version" >= 1)
);
--> statement-breakpoint
CREATE INDEX `ai_channels_enabled_area_provider_idx` ON `ai_channels` (`enabled`,`area`,`provider`);--> statement-breakpoint
CREATE TABLE `oauth_authorization_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`client_id` text NOT NULL,
	`device_code_hash` text NOT NULL,
	`user_code_hash` text NOT NULL,
	`state_hash` text NOT NULL,
	`code_challenge` text NOT NULL,
	`code_challenge_method` text NOT NULL,
	`requested_scopes` text NOT NULL,
	`status` text NOT NULL,
	`grant_id` text,
	`authorization_code` text,
	`expires_at` integer NOT NULL,
	`code_expires_at` integer,
	`last_polled_at` integer,
	`created_at` integer NOT NULL,
	`consumed_at` integer,
	FOREIGN KEY (`client_id`) REFERENCES `oauth_client`(`client_id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`grant_id`) REFERENCES `oauth_grants`(`id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "oauth_authorization_requests_code_challenge_method_check" CHECK("oauth_authorization_requests"."code_challenge_method" = 'S256'),
	CONSTRAINT "oauth_authorization_requests_status_check" CHECK("oauth_authorization_requests"."status" in ('pending', 'authorized', 'denied', 'expired', 'consumed')),
	CONSTRAINT "oauth_authorization_requests_expiry_check" CHECK("oauth_authorization_requests"."expires_at" > "oauth_authorization_requests"."created_at")
);
--> statement-breakpoint
CREATE UNIQUE INDEX `oauth_authorization_requests_device_code_hash_unique` ON `oauth_authorization_requests` (`device_code_hash`);--> statement-breakpoint
CREATE UNIQUE INDEX `oauth_authorization_requests_user_code_hash_unique` ON `oauth_authorization_requests` (`user_code_hash`);--> statement-breakpoint
CREATE UNIQUE INDEX `oauth_authorization_requests_state_hash_unique` ON `oauth_authorization_requests` (`state_hash`);--> statement-breakpoint
CREATE UNIQUE INDEX `oauth_authorization_requests_grant_id_unique` ON `oauth_authorization_requests` (`grant_id`);--> statement-breakpoint
CREATE INDEX `oauth_authorization_requests_status_expires_at_idx` ON `oauth_authorization_requests` (`status`,`expires_at`);--> statement-breakpoint
CREATE TABLE `oauth_grants` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`client_id` text NOT NULL,
	`scopes` text NOT NULL,
	`status` text NOT NULL,
	`created_at` integer NOT NULL,
	`approved_at` integer,
	`revoked_at` integer,
	FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`client_id`) REFERENCES `oauth_client`(`client_id`) ON UPDATE no action ON DELETE no action,
	CONSTRAINT "oauth_grants_status_check" CHECK("oauth_grants"."status" in ('pending', 'active', 'revoked'))
);
--> statement-breakpoint
CREATE INDEX `oauth_grants_user_id_status_idx` ON `oauth_grants` (`user_id`,`status`);--> statement-breakpoint
CREATE INDEX `oauth_grants_client_id_status_idx` ON `oauth_grants` (`client_id`,`status`);--> statement-breakpoint
CREATE TABLE `payment_products` (
	`id` text PRIMARY KEY NOT NULL,
	`type` text NOT NULL,
	`credits_amount` integer,
	`subscription_plan` text,
	`upgrade_rank` integer,
	`period_credits_amount` integer,
	`dodo_product_id` text,
	`creem_product_id` text,
	`version` integer NOT NULL,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "payment_products_type_check" CHECK("payment_products"."type" in ('one_time', 'subscription')),
	CONSTRAINT "payment_products_provider_check" CHECK("payment_products"."dodo_product_id" is not null or "payment_products"."creem_product_id" is not null),
	CONSTRAINT "payment_products_fields_check" CHECK(("payment_products"."type" = 'one_time' and "payment_products"."credits_amount" > 0 and "payment_products"."subscription_plan" is null and "payment_products"."upgrade_rank" is null and "payment_products"."period_credits_amount" is null) or ("payment_products"."type" = 'subscription' and "payment_products"."credits_amount" is null and "payment_products"."subscription_plan" is not null and length("payment_products"."subscription_plan") > 0 and "payment_products"."upgrade_rank" >= 0 and "payment_products"."period_credits_amount" > 0)),
	CONSTRAINT "payment_products_version_check" CHECK("payment_products"."version" >= 1)
);
--> statement-breakpoint
CREATE UNIQUE INDEX `payment_products_dodo_product_id_unique` ON `payment_products` (`dodo_product_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `payment_products_creem_product_id_unique` ON `payment_products` (`creem_product_id`);--> statement-breakpoint
CREATE TABLE `system_settings` (
	`id` integer PRIMARY KEY NOT NULL,
	`general_version` integer NOT NULL,
	`authentication_version` integer NOT NULL,
	`email_version` integer NOT NULL,
	`storage_version` integer NOT NULL,
	`credits_version` integer NOT NULL,
	`affiliate_version` integer NOT NULL,
	`payment_version` integer NOT NULL,
	`ai_version` integer NOT NULL,
	`design_system` text NOT NULL,
	`docs_enabled` integer NOT NULL,
	`beta_code_enabled` integer NOT NULL,
	`email_signup_enabled` integer NOT NULL,
	`email_signup_domain_allowlist` text NOT NULL,
	`email_require_verification` integer NOT NULL,
	`email_user_action_cooldown_seconds` integer NOT NULL,
	`turnstile_enabled` integer NOT NULL,
	`turnstile_site_key` text,
	`turnstile_secret_key_ciphertext` text,
	`turnstile_secret_key_iv` text,
	`google_auth_enabled` integer NOT NULL,
	`google_client_id` text,
	`google_client_secret_ciphertext` text,
	`google_client_secret_iv` text,
	`github_auth_enabled` integer NOT NULL,
	`github_client_id` text,
	`github_client_secret_ciphertext` text,
	`github_client_secret_iv` text,
	`linuxdo_auth_enabled` integer NOT NULL,
	`linuxdo_client_id` text,
	`linuxdo_client_secret_ciphertext` text,
	`linuxdo_client_secret_iv` text,
	`email_enabled` integer NOT NULL,
	`email_provider` text,
	`email_resend_api_key_ciphertext` text,
	`email_resend_api_key_iv` text,
	`r2_user_upload_allowed_content_types` text NOT NULL,
	`r2_user_upload_max_bytes` integer NOT NULL,
	`credits_signup_enabled` integer NOT NULL,
	`credits_signup_amount` integer NOT NULL,
	`credits_daily_checkin_enabled` integer NOT NULL,
	`credits_daily_checkin_amount` integer NOT NULL,
	`credits_history_retention_days` integer NOT NULL,
	`affiliate_enabled` integer NOT NULL,
	`affiliate_inviter_credit_amount` integer NOT NULL,
	`affiliate_invitee_credit_amount` integer NOT NULL,
	`payment_enabled` integer NOT NULL,
	`payment_default_provider` text,
	`payment_provider_country_overrides` text NOT NULL,
	`payment_dodo_test_mode` integer NOT NULL,
	`payment_dodo_api_key_ciphertext` text,
	`payment_dodo_api_key_iv` text,
	`payment_dodo_webhook_secret_ciphertext` text,
	`payment_dodo_webhook_secret_iv` text,
	`payment_creem_test_mode` integer NOT NULL,
	`payment_creem_api_key_ciphertext` text,
	`payment_creem_api_key_iv` text,
	`payment_creem_webhook_secret_ciphertext` text,
	`payment_creem_webhook_secret_iv` text,
	`ai_routing_error_weight` real NOT NULL,
	`ai_routing_latency_weight` real NOT NULL,
	`ai_routing_price_weight` real NOT NULL,
	`ai_task_retention_days` integer NOT NULL,
	`chat_openai_enabled` integer NOT NULL,
	`chat_openai_base_url` text,
	`chat_openai_default_model` text,
	`chat_openai_api_key_ciphertext` text,
	`chat_openai_api_key_iv` text,
	`image_gemini_enabled` integer NOT NULL,
	`image_gemini_base_url` text,
	`image_gemini_default_model` text,
	`image_gemini_api_key_ciphertext` text,
	`image_gemini_api_key_iv` text,
	`image_openai_enabled` integer NOT NULL,
	`image_openai_base_url` text,
	`image_openai_default_model` text,
	`image_openai_api_key_ciphertext` text,
	`image_openai_api_key_iv` text,
	`image_seedream_enabled` integer NOT NULL,
	`image_seedream_base_url` text,
	`image_seedream_default_model` text,
	`image_seedream_api_key_ciphertext` text,
	`image_seedream_api_key_iv` text,
	`image_aliyun_enabled` integer NOT NULL,
	`image_aliyun_base_url` text,
	`image_aliyun_default_model` text,
	`image_aliyun_api_key_ciphertext` text,
	`image_aliyun_api_key_iv` text,
	`tts_gemini_enabled` integer NOT NULL,
	`tts_gemini_base_url` text,
	`tts_gemini_default_model` text,
	`tts_gemini_api_key_ciphertext` text,
	`tts_gemini_api_key_iv` text,
	`tts_seed_enabled` integer NOT NULL,
	`tts_seed_base_url` text,
	`tts_seed_default_model` text,
	`tts_seed_api_key_ciphertext` text,
	`tts_seed_api_key_iv` text,
	`realtime_doubao_enabled` integer NOT NULL,
	`realtime_doubao_base_url` text,
	`realtime_doubao_default_model` text,
	`realtime_doubao_api_key_ciphertext` text,
	`realtime_doubao_api_key_iv` text,
	`video_seedance_enabled` integer NOT NULL,
	`video_seedance_base_url` text,
	`video_seedance_default_model` text,
	`video_seedance_api_key_ciphertext` text,
	`video_seedance_api_key_iv` text,
	`created_at` integer NOT NULL,
	`updated_at` integer NOT NULL,
	CONSTRAINT "system_settings_singleton_check" CHECK("system_settings"."id" = 1),
	CONSTRAINT "system_settings_versions_check" CHECK("system_settings"."general_version" >= 1 and "system_settings"."authentication_version" >= 1 and "system_settings"."email_version" >= 1 and "system_settings"."storage_version" >= 1 and "system_settings"."credits_version" >= 1 and "system_settings"."affiliate_version" >= 1 and "system_settings"."payment_version" >= 1 and "system_settings"."ai_version" >= 1),
	CONSTRAINT "system_settings_design_system_check" CHECK("system_settings"."design_system" in ('apple-saas', 'brutalism')),
	CONSTRAINT "system_settings_email_provider_check" CHECK("system_settings"."email_provider" is null or "system_settings"."email_provider" in ('cloudflare', 'resend')),
	CONSTRAINT "system_settings_payment_provider_check" CHECK("system_settings"."payment_default_provider" is null or "system_settings"."payment_default_provider" in ('dodo', 'creem')),
	CONSTRAINT "system_settings_positive_values_check" CHECK("system_settings"."email_user_action_cooldown_seconds" > 0 and "system_settings"."r2_user_upload_max_bytes" > 0 and "system_settings"."credits_signup_amount" >= 0 and "system_settings"."credits_daily_checkin_amount" >= 0 and "system_settings"."credits_history_retention_days" > 0 and "system_settings"."affiliate_inviter_credit_amount" >= 0 and "system_settings"."affiliate_invitee_credit_amount" >= 0 and "system_settings"."ai_routing_error_weight" >= 0 and "system_settings"."ai_routing_latency_weight" >= 0 and "system_settings"."ai_routing_price_weight" >= 0 and ("system_settings"."ai_routing_error_weight" + "system_settings"."ai_routing_latency_weight" + "system_settings"."ai_routing_price_weight") > 0 and "system_settings"."ai_task_retention_days" > 0)
);
--> statement-breakpoint
INSERT INTO `system_settings` (
	`id`,
	`general_version`,
	`authentication_version`,
	`email_version`,
	`storage_version`,
	`credits_version`,
	`affiliate_version`,
	`payment_version`,
	`ai_version`,
	`design_system`,
	`docs_enabled`,
	`beta_code_enabled`,
	`email_signup_enabled`,
	`email_signup_domain_allowlist`,
	`email_require_verification`,
	`email_user_action_cooldown_seconds`,
	`turnstile_enabled`,
	`turnstile_site_key`,
	`turnstile_secret_key_ciphertext`,
	`turnstile_secret_key_iv`,
	`google_auth_enabled`,
	`google_client_id`,
	`google_client_secret_ciphertext`,
	`google_client_secret_iv`,
	`github_auth_enabled`,
	`github_client_id`,
	`github_client_secret_ciphertext`,
	`github_client_secret_iv`,
	`linuxdo_auth_enabled`,
	`linuxdo_client_id`,
	`linuxdo_client_secret_ciphertext`,
	`linuxdo_client_secret_iv`,
	`email_enabled`,
	`email_provider`,
	`email_resend_api_key_ciphertext`,
	`email_resend_api_key_iv`,
	`r2_user_upload_allowed_content_types`,
	`r2_user_upload_max_bytes`,
	`credits_signup_enabled`,
	`credits_signup_amount`,
	`credits_daily_checkin_enabled`,
	`credits_daily_checkin_amount`,
	`credits_history_retention_days`,
	`affiliate_enabled`,
	`affiliate_inviter_credit_amount`,
	`affiliate_invitee_credit_amount`,
	`payment_enabled`,
	`payment_default_provider`,
	`payment_provider_country_overrides`,
	`payment_dodo_test_mode`,
	`payment_dodo_api_key_ciphertext`,
	`payment_dodo_api_key_iv`,
	`payment_dodo_webhook_secret_ciphertext`,
	`payment_dodo_webhook_secret_iv`,
	`payment_creem_test_mode`,
	`payment_creem_api_key_ciphertext`,
	`payment_creem_api_key_iv`,
	`payment_creem_webhook_secret_ciphertext`,
	`payment_creem_webhook_secret_iv`,
	`ai_routing_error_weight`,
	`ai_routing_latency_weight`,
	`ai_routing_price_weight`,
	`ai_task_retention_days`,
	`chat_openai_enabled`,
	`chat_openai_base_url`,
	`chat_openai_default_model`,
	`chat_openai_api_key_ciphertext`,
	`chat_openai_api_key_iv`,
	`image_gemini_enabled`,
	`image_gemini_base_url`,
	`image_gemini_default_model`,
	`image_gemini_api_key_ciphertext`,
	`image_gemini_api_key_iv`,
	`image_openai_enabled`,
	`image_openai_base_url`,
	`image_openai_default_model`,
	`image_openai_api_key_ciphertext`,
	`image_openai_api_key_iv`,
	`image_seedream_enabled`,
	`image_seedream_base_url`,
	`image_seedream_default_model`,
	`image_seedream_api_key_ciphertext`,
	`image_seedream_api_key_iv`,
	`image_aliyun_enabled`,
	`image_aliyun_base_url`,
	`image_aliyun_default_model`,
	`image_aliyun_api_key_ciphertext`,
	`image_aliyun_api_key_iv`,
	`tts_gemini_enabled`,
	`tts_gemini_base_url`,
	`tts_gemini_default_model`,
	`tts_gemini_api_key_ciphertext`,
	`tts_gemini_api_key_iv`,
	`tts_seed_enabled`,
	`tts_seed_base_url`,
	`tts_seed_default_model`,
	`tts_seed_api_key_ciphertext`,
	`tts_seed_api_key_iv`,
	`realtime_doubao_enabled`,
	`realtime_doubao_base_url`,
	`realtime_doubao_default_model`,
	`realtime_doubao_api_key_ciphertext`,
	`realtime_doubao_api_key_iv`,
	`video_seedance_enabled`,
	`video_seedance_base_url`,
	`video_seedance_default_model`,
	`video_seedance_api_key_ciphertext`,
	`video_seedance_api_key_iv`,
	`created_at`,
	`updated_at`
) VALUES (
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	1,
	'apple-saas',
	1,
	0,
	0,
	'[]',
	0,
	50,
	0,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	'["image/png","image/jpeg","image/webp"]',
	5242880,
	0,
	100000000,
	0,
	10000000,
	90,
	0,
	50000000,
	20000000,
	0,
	NULL,
	'[]',
	1,
	NULL,
	NULL,
	NULL,
	NULL,
	1,
	NULL,
	NULL,
	NULL,
	NULL,
	1,
	0.8,
	0.2,
	30,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	0,
	NULL,
	NULL,
	NULL,
	NULL,
	cast(unixepoch('subsecond') * 1000 as integer),
	cast(unixepoch('subsecond') * 1000 as integer)
);
--> statement-breakpoint
CREATE INDEX `oauthAccessToken_referenceId_idx` ON `oauth_access_token` (`reference_id`);--> statement-breakpoint
CREATE INDEX `oauthRefreshToken_referenceId_idx` ON `oauth_refresh_token` (`reference_id`);
