/// <reference path="../worker-configuration.d.ts" />

import { api } from './backend/api'
import { handleScheduled } from './backend/jobs'
import { handleQueue } from './backend/consumers'

// This file is generated by vite build before Wrangler starts.
// @ts-ignore
import svelteWorker from '../.svelte-kit/cloudflare/_worker.js'

export function main(): Entrypoint {
	return {
		fetch: async (request, env, ctx): Promise<Response> => {
			try {
				if (isApiRequest(request)) {
					return api.fetch(request, env, ctx)
				}
				return svelteWorker.fetch(request, env, ctx)
			} catch (error) {
				const message = error instanceof Error ? error.message : 'Unknown error'
				console.error(
					JSON.stringify({
						message: 'unhandled error',
						error: message,
						path: new URL(request.url).pathname
					})
				)

				return Response.json({ error: 'Internal server error' }, { status: 500 })
			}
		},

		scheduled: async (controller, env, ctx): Promise<void> => {
			return handleScheduled(controller, env, ctx)
		},

		queue: async (batch, env, ctx): Promise<void> => {
			return handleQueue(batch, env, ctx)
		}
	}
}

export default main() as ExportedHandler<WorkerEnv>

function isApiRequest(request: Request): boolean {
	return new URL(request.url).pathname.startsWith('/api/')
}

export type WorkerEnv = Env

export interface Entrypoint {
	fetch: FetchHandler
	scheduled: ScheduledHandler
	queue: QueueHandler
}

export type FetchHandler = (
	request: Request,
	env: WorkerEnv,
	ctx: ExecutionContext
) => Promise<Response>

export type ScheduledHandler = (
	controller: ScheduledController,
	env: WorkerEnv,
	ctx: ExecutionContext
) => Promise<void>

export type QueueHandler = (
	batch: MessageBatch<unknown>,
	env: WorkerEnv,
	ctx: ExecutionContext
) => Promise<void>
